[package]
name = "trackable"
version = "0.2.4"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "This library provides a way to track objects manually as an alternative to mechanisms like backtracing"
homepage = "https://github.com/sile/trackable"
repository = "https://github.com/sile/trackable"
readme = "README.md"
license = "MIT"

[badges]
travis-ci = {repository = "sile/trackable"}
codecov = {repository = "sile/trackable"}

[dependencies]
rand = "0.3"
