[package]
name = "trackable"
version = "0.1.7"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "This library provides a way to track objects manually as an alternative to mechanisms like backtracing"
documentation = "https://docs.rs/trackable"
homepage = "https://github.com/sile/trackable"
repository = "https://github.com/sile/trackable"
readme = "README.md"
license = "MIT"

[badges]
travis-ci = {repository = "sile/trackable"}

[dependencies]
rand = "0.3"
